services:
  db:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=password_seguro

  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - ARANGO_URL=http://db:8529
      - ARANGO_PWD=password_seguro
      - PYTHONPATH=/app
    command: bash -c "PYTHONPATH=/app python -u data/setup_data.py && streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0"